import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")||"",SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const RAZOR_ID=Deno.env.get("RAZORPAY_KEY_ID_LIVE")||"",RAZOR_SECRET=Deno.env.get("RAZORPAY_KEY_SECRET_LIVE")||"";
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(["https://clarionprep.com","https://www.clarionprep.com","https://pcl-professional-communication-lab.pages.dev"]);
const clean=(v:unknown)=>String(v??"").trim();
function headers(req:Request){const o=clean(req.headers.get("origin"));return{"Access-Control-Allow-Origin":ORIGINS.has(o)?o:"https://clarionprep.com","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
const out=(req:Request,body:Record<string,unknown>,status=200)=>new Response(JSON.stringify(body),{status,headers:headers(req)});
function bearer(req:Request){const h=clean(req.headers.get("authorization"));return h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():""}
async function user(req:Request){const token=bearer(req);if(!token)return null;const {data,error}=await db.auth.getUser(token);return error?null:data.user}
function receipt(){return `clarion_${Date.now().toString(36)}_${crypto.randomUUID().replaceAll("-","").slice(0,10)}`}
async function hmac(message:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(RAZOR_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(message)));return Array.from(sig).map(x=>x.toString(16).padStart(2,"0")).join("")}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function provider(path:string,init:RequestInit={}){const r=await fetch(`https://api.razorpay.com/v1/${path}`,{...init,headers:{Authorization:`Basic ${btoa(`${RAZOR_ID}:${RAZOR_SECRET}`)}`,Accept:"application/json",...(init.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(clean(body?.error?.description)||"Razorpay could not complete the request.");return body}
async function catalogue(req:Request){const {data,error}=await db.from("clarion_products").select("code,display_name,amount_paise,currency,duration_days,usage_limit,usage_label,launch_url").eq("is_active",true).order("sort_order");if(error)throw error;return out(req,{ok:true,products:data||[]})}
async function createOrder(req:Request,b:any){const u=await user(req);if(!u)return out(req,{ok:false,message:"Sign in to your ClarionPrep account first."},401);const code=clean(b.product_code).toUpperCase();const {data:p,error}=await db.from("clarion_products").select("*").eq("code",code).eq("is_active",true).maybeSingle();if(error)throw error;if(!p)return out(req,{ok:false,message:"This subscription is not currently available."},404);const name=clean(b.full_name).slice(0,120),phone=clean(b.mobile).slice(0,30),email=clean(u.email).toLowerCase();if(name.length<2)return out(req,{ok:false,message:"Enter your full name."},400);const rp=await provider("orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:p.amount_paise,currency:p.currency,receipt:receipt(),notes:{product_code:code,user_id:u.id}})});const {data:o,error:oe}=await db.from("clarion_product_payment_orders").insert({user_id:u.id,product_code:code,buyer_name:name,buyer_email:email,buyer_phone:phone||null,amount_paise:p.amount_paise,currency:p.currency,razorpay_order_id:rp.id,provider_response:{order:rp}}).select("id").single();if(oe)throw oe;return out(req,{ok:true,payment_order_uuid:o.id,razorpay_order_id:rp.id,razorpay_key_id:RAZOR_ID,amount_paise:p.amount_paise,currency:p.currency,product:p})}
async function verify(req:Request,b:any){const u=await user(req);if(!u)return out(req,{ok:false,message:"Your ClarionPrep session has expired."},401);const id=clean(b.payment_order_uuid),pay=clean(b.razorpay_payment_id),order=clean(b.razorpay_order_id),sig=clean(b.razorpay_signature).toLowerCase();const {data:o,error}=await db.from("clarion_product_payment_orders").select("*").eq("id",id).eq("user_id",u.id).maybeSingle();if(error)throw error;if(!o)return out(req,{ok:false,message:"The payment order was not found."},404);if(o.payment_status==="PAID"){const {data:e}=await db.from("clarion_product_entitlements").select("*").eq("user_id",u.id).eq("product_code",o.product_code).single();return out(req,{ok:true,already_verified:true,entitlement:e})}if(o.razorpay_order_id!==order)return out(req,{ok:false,message:"The Razorpay order does not match."},409);const expected=await hmac(`${order}|${pay}`);if(!/^[a-f0-9]{64}$/.test(sig)||!safeEqual(expected,sig))return out(req,{ok:false,message:"Razorpay could not verify this payment."},401);let payment=await provider(`payments/${encodeURIComponent(pay)}`);if(payment.order_id!==order||Number(payment.amount)!==Number(o.amount_paise)||clean(payment.currency).toUpperCase()!==o.currency)return out(req,{ok:false,message:"The captured payment does not match this order."},409);if(payment.status==="authorized")payment=await provider(`payments/${encodeURIComponent(pay)}/capture`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:o.amount_paise,currency:o.currency})});if(payment.status!=="captured")return out(req,{ok:false,message:"The payment has not been captured."},409);const {data:p}=await db.from("clarion_products").select("launch_url,display_name").eq("code",o.product_code).single();const {data:finalized,error:fe}=await db.rpc("clarion_finalize_product_payment",{p_order_id:id,p_user_id:u.id,p_payment_id:pay,p_provider_response:{payment}});if(fe)throw fe;return out(req,{ok:true,message:"Payment confirmed. Your access is active.",entitlement:finalized?.entitlement,already_verified:finalized?.already_verified===true,launch_url:p.launch_url,display_name:p.display_name})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});const origin=clean(req.headers.get("origin"));if(origin&&!ORIGINS.has(origin))return out(req,{ok:false,message:"Origin not allowed."},403);if(req.method!=="POST")return out(req,{ok:false,message:"Use POST."},405);if(!URL||!SERVICE||!RAZOR_ID||!RAZOR_SECRET)return out(req,{ok:false,message:"Subscription service is not configured."},503);try{const b=await req.json().catch(()=>({})),action=clean(b.action).toUpperCase();if(action==="CATALOG")return await catalogue(req);if(action==="CREATE_ORDER")return await createOrder(req,b);if(action==="VERIFY")return await verify(req,b);return out(req,{ok:false,message:"Invalid action."},400)}catch(e){console.error("clarion-product-commerce",e);return out(req,{ok:false,message:clean(e?.message)||"Subscription request failed."},500)}});
