(function(){
  'use strict';
  const box=document.querySelector('[data-ai-conversation]'),U=window.ORACY_UNIT;
  if(!box||!U)return;
  const cfg=U.conversation||{},maxTurns=Number(cfg.maxLearnerTurns||4);
  const log=box.querySelector('.conversation-log'),state=box.querySelector('.conversation-state'),light=box.querySelector('.mic-light'),startBtn=box.querySelector('.start-conversation'),endBtn=box.querySelector('.end-conversation'),status=box.querySelector('.status'),feedback=box.querySelector('.feedback');
  let pc=null,dc=null,stream=null,remoteAudio=null,started=false,ending=false,userTurns=0,assistantTurns=0,history=[],assistantBuffer='',feedbackRequested=false;
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function bubble(who,text){if(!text)return;const el=document.createElement('div');el.className='conversation-bubble '+who;el.innerHTML='<b>'+(who==='coach'?'Coach':'You')+':</b> '+esc(text);log.appendChild(el);log.scrollTop=log.scrollHeight}
  function setState(text,on=true){state.textContent=text;light.classList.toggle('on',on)}
  function closePeer(message='Conversation ended.'){ending=true;try{dc?.close()}catch{}try{pc?.close()}catch{}stream?.getTracks().forEach(t=>t.stop());if(remoteAudio){remoteAudio.pause();remoteAudio.srcObject=null}pc=dc=stream=remoteAudio=null;started=false;light.classList.remove('on');state.textContent=message;startBtn.classList.remove('hidden');startBtn.textContent=userTurns?'🎤 Start again':'🎤 Start conversation';endBtn.classList.add('hidden')}
  function friendlyError(e){const n=e?.name||'';if(n==='NotAllowedError')return 'Please allow microphone access to start the conversation.';if(n==='NotFoundError')return 'No microphone was found.';return e?.message||'The live conversation could not start.'}
  async function gateway(action,extra={}){const r=await fetch('/oracy/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,unit_no:U.unitNo,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.message||'The ORACY conversation service is unavailable.');return d}
  function renderFeedback(r){const line=(title,item)=>'<div><b>'+title+': '+(Number(item?.score||0)||'–')+'/3</b><br>'+esc(item?.comment||'Keep practising with one clear sentence at a time.')+'</div>';feedback.innerHTML='<b>Coach feedback</b>'+line('Task completed',r.task_achievement)+line('Words and expressions',r.range)+line('Sentences',r.accuracy)+line('Flow',r.fluency)+line('Easy to follow',r.coherence)+'<div><b>Pronunciation and voice: not scored here</b><br>'+esc(r.phonological_control?.comment||'Fine pronunciation cannot be judged reliably from a transcript alone.')+'</div><div class="model"><b>Try this first:</b> “'+esc(r.improved_version||'Certainly. Could you lend me a bowl, please? I’ll return it tomorrow morning.')+'”<br><b>Now make one of your own:</b> '+esc(r.next_step||'Change the object and the return time.')+'</div>'}
  async function finishWithFeedback(){if(feedbackRequested)return;feedbackRequested=true;setState('Preparing your feedback…',false);try{const d=await gateway('conversation-feedback',{history,conversation:cfg});renderFeedback(d.rubric||{});closePeer('Four turns complete. Well done.')}catch(e){status.textContent=e.message;closePeer('Conversation complete.')}}
  function handleEvent(raw){let e;try{e=JSON.parse(raw)}catch{return}
    if(e.type==='input_audio_buffer.speech_started'){setState('Listening — speak naturally');return}
    if(e.type==='input_audio_buffer.speech_stopped'){setState('Coach is responding…');return}
    if(e.type==='conversation.item.input_audio_transcription.completed'){const text=String(e.transcript||'').trim();if(text){userTurns++;history.push({role:'learner',text});bubble('learner',text)}return}
    if(e.type==='response.output_audio_transcript.delta'){assistantBuffer+=String(e.delta||'');return}
    if(e.type==='response.output_audio_transcript.done'){const text=String(e.transcript||assistantBuffer).trim();assistantBuffer='';if(text){assistantTurns++;history.push({role:'coach',text});bubble('coach',text)}return}
    if(e.type==='response.audio_transcript.delta'){assistantBuffer+=String(e.delta||'');return}
    if(e.type==='response.audio_transcript.done'){const text=String(e.transcript||assistantBuffer).trim();assistantBuffer='';if(text){assistantTurns++;history.push({role:'coach',text});bubble('coach',text)}return}
    if(e.type==='response.created'){setState('Coach is responding…');return}
    if(e.type==='response.done'){if(userTurns>=maxTurns||assistantTurns>=maxTurns){finishWithFeedback()}else setState('Microphone on — your turn');return}
    if(e.type==='error'){status.textContent=e.error?.message||'The live conversation reported an error.'}
  }
  async function start(){if(started)return;try{ending=false;feedbackRequested=false;userTurns=assistantTurns=0;history=[];assistantBuffer='';feedback.innerHTML='';log.innerHTML='<div class="conversation-bubble coach"><b>Coach:</b> I’m ready. You start the conversation.</div>';setState('Connecting…',false);startBtn.disabled=true;stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const token=await gateway('realtime-token',{conversation:cfg});if(!token.client_secret)throw new Error('ORACY did not receive a valid live-conversation token.');pc=new RTCPeerConnection();remoteAudio=new Audio();remoteAudio.autoplay=true;pc.ontrack=e=>{remoteAudio.srcObject=e.streams[0];remoteAudio.play().catch(()=>{})};stream.getTracks().forEach(track=>pc.addTrack(track,stream));dc=pc.createDataChannel('oai-events');dc.onmessage=e=>handleEvent(e.data);dc.onerror=()=>{if(!ending)status.textContent='The live conversation connection reported an error.'};dc.onopen=()=>{started=true;startBtn.classList.add('hidden');endBtn.classList.remove('hidden');status.textContent='The microphone stays on. The coach will respond as soon as you finish speaking, and you may interrupt naturally.';setState('Microphone on. You start.')};pc.onconnectionstatechange=()=>{if(!pc||ending)return;const s=pc.connectionState;if(s==='failed'||s==='closed'){status.textContent='The live connection ended. Please start again.';closePeer('Connection ended.')}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const r=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',body:offer.sdp,headers:{Authorization:'Bearer '+token.client_secret,'Content-Type':'application/sdp'}});const answer=await r.text();if(!r.ok)throw new Error('OpenAI Realtime could not start. '+answer.slice(0,180));await pc.setRemoteDescription({type:'answer',sdp:answer})}catch(e){status.textContent=friendlyError(e);closePeer('Microphone off')}finally{startBtn.disabled=false}}
  startBtn.addEventListener('click',start);endBtn.addEventListener('click',()=>closePeer());
  addEventListener('pagehide',()=>closePeer('Microphone off'));
  addEventListener('beforeunload',()=>closePeer('Microphone off'));
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&started)closePeer('Paused because you left the page.')});
})();