// ORACY Unit 1: three Key Point speaking gyms plus vocabulary-in-use drills.
const ORACY_KP_CONFIG=[
 {title:'Languages around you',vocab:['native language','official language','at least','almost','majority'],reps:[
  ['Free answer','Languages in your world','Speak for 30–40 seconds about the languages around you.','Speak for 30 to 40 seconds about the languages around you.'],
  ['Compress','Same idea. Less time.','Give the same message in 20–25 seconds and use at least one Key Point 1 vocabulary item.','Give the same message in 20 to 25 seconds and use at least one of: native language, official language, at least, almost, majority.'],
  ['Target language','Use the vocabulary','Answer again in 25–30 seconds using at least three of the five Key Point 1 vocabulary items.','Answer again in 25 to 30 seconds using at least three of: native language, official language, at least, almost, majority.'],
  ['React','The coach pushes back','Complete Rep 3 first. The coach will challenge something you actually said.','Respond directly to the coach challenge in 20 to 30 seconds.'],
  ['Pressure finish','Land the point','Final rep: about 20 seconds. Use at least two Key Point 1 vocabulary items.','In about 20 seconds, give one clear picture of the language situation around you and use at least two Key Point 1 vocabulary items.']
 ]},
 {title:'Why you use and learn English',vocab:['goal','practise','improve','communicate','confidence'],reps:[
  ['Free answer','Why English matters to you','Speak for 30–40 seconds about what you use English for and why you are learning it.','Speak for 30 to 40 seconds about what you use English for and why you are learning it.'],
  ['Compress','Keep the purpose clear','Give the same answer in 20–25 seconds. Keep one main purpose and one detail.','Give the same answer in 20 to 25 seconds. Keep one main purpose and one detail.'],
  ['Target language','Use the purpose patterns','Use at least two purpose patterns and at least two Key Point 2 vocabulary items.','Use at least two of: I use ... for -ing, I need ... to, I am learning ... to, so that I can. Also use at least two of: goal, practise, improve, communicate, confidence.'],
  ['React','Defend the reason','Complete Rep 3 first. The coach will question one of your reasons.','Respond directly to the coach challenge and explain why your reason matters.'],
  ['Pressure finish','Purpose in 20 seconds','Say what you need English for, why, and what you want to improve.','In about 20 seconds, use one purpose pattern and at least two of: goal, practise, improve, communicate, confidence.']
 ]},
 {title:'/w/ and /v/ in real speech',vocab:['work','world','visit','video','travel'],reps:[
  ['Free answer','Talk about your week','Speak for 30–40 seconds about work, people you visit, videos you watch, or places you want to travel to.','Speak for 30 to 40 seconds about work, people you visit, videos you watch, or places you want to travel to.'],
  ['Compress','Same message. Cleaner sounds.','Give the same message in 20–25 seconds and keep /w/ and /v/ words clear.','Give the same message in 20 to 25 seconds and keep w and v words clear.'],
  ['Target language','Use all five sound words','Use all five words naturally: work, world, visit, video, travel.','Answer in 25 to 30 seconds and use all five words: work, world, visit, video, travel.'],
  ['React','Answer without losing clarity','Complete Rep 3 first. The coach will react to one detail you gave.','Respond directly in 20 to 30 seconds while keeping the target w and v words clear.'],
  ['Pressure finish','Clear under pressure','Final rep: about 20 seconds. Use at least three target words.','In about 20 seconds, use at least three of: work, world, visit, video, travel.']
 ]}
];
function oNorm(v){return String(v||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim();}
function oHas(t,v){return oNorm(t).includes(oNorm(v));}
function oWords(t){return oNorm(t).split(' ').filter(Boolean).length;}
function oPurposeCount(t){const s=oNorm(t);return [/\bi use\b.{0,70}\bfor\b/,/\bi need\b.{0,70}\bto\b/,/\bi(?:'m| am) learning\b.{0,70}\bto\b/,/so that i can\b/].filter(r=>r.test(s)).length;}
function oChallenge(kp,t){const s=String(t||'').replace(/\s+/g,' ').trim();const short=s.length>90?s.slice(0,87)+'…':s;if(kp===0)return short?`Coach: You said, “${short}” Give me one real example that proves it.`:'Coach: Give me one real example.';if(kp===1)return short?`Coach: You said, “${short}” Why is that reason important enough for you to keep practising?`:'Coach: What is your strongest reason for improving English?';return short?`Coach: You said, “${short}” Add one more detail while keeping /w/ and /v/ clear.`:'Coach: Add one detail using a /w/ word and a /v/ word.';}
function oMakeSpeak(kp,rep,spec){const b=document.createElement('div');b.className='speak';b.dataset.kpIndex=kp;b.dataset.repIndex=rep;b.innerHTML=`<div class="eyebrow">Rep ${rep+1} · ${safe(spec[0])}</div><p><b>${safe(spec[1])}</b></p><p>${safe(spec[2])}</p>${rep===3?'<div class="oracy-reactive-challenge" style="margin:12px 0;padding:12px;border-radius:10px;background:#eef4ff;border:1px solid #b8caee"><b>Coach challenge</b><div style="margin-top:5px">Complete Rep 3 first.</div></div>':''}<button class="record" data-prompt="${safe(spec[3])}">🎤 Start Rep ${rep+1}</button><div class="oracy-rep-lock" style="margin:8px 0"></div><div class="status"></div><div class="feedback"></div>`;return b;}
function oBuild(){const hero=document.querySelector('.hero p');if(hero)hero.innerHTML='<b>Unit design:</b> 3 Key Points · 5 vocabulary items per Key Point · 5 core speaking reps per Key Point · 5 vocabulary drills per Key Point.';const secs=[...document.querySelectorAll('section.kp')].slice(0,3);secs.forEach((sec,kp)=>{sec.querySelectorAll('.speak').forEach(x=>x.remove());const cfg=ORACY_KP_CONFIG[kp];const old=sec.querySelector('.chips');if(old)old.remove();const v=document.createElement('div');v.className='activity oracy-vocab-five';v.innerHTML=`<div class="eyebrow">Vocabulary · 5 items</div><h3>Five useful items for this Key Point</h3><div class="chips">${cfg.vocab.map(x=>`<span>${safe(x)}</span>`).join('')}</div><p>Do not only learn these words. You will use every item in a 3-turn conversation drill below.</p>`;sec.querySelector('h2')?.insertAdjacentElement('afterend',v);const gym=document.createElement('div');gym.className='oracy-speaking-gym';gym.dataset.kpIndex=kp;gym.innerHTML=`<div class="eyebrow">Speaking Gym · Key Point ${kp+1} · 5 reps</div><h3>${safe(cfg.title)}</h3><p>Repeat the same skill under changing constraints. Each rep unlocks the next.</p>`;cfg.reps.forEach((s,r)=>gym.appendChild(oMakeSpeak(kp,r,s)));sec.appendChild(gym);});}
function oBox(kp,rep){return document.querySelector(`.speak[data-kp-index="${kp}"][data-rep-index="${rep}"]:not(.oracy-vocab-drill)`);}
function oLock(kp,rep,locked){const b=oBox(kp,rep);if(!b)return;const btn=b.querySelector('.record'),n=b.querySelector('.oracy-rep-lock');if(btn)btn.disabled=locked;if(n)n.textContent=locked?`Complete Rep ${rep} first.`:'Ready for this rep.';}
function oConstraint(kp,rep,t){const cfg=ORACY_KP_CONFIG[kp],w=oWords(t),hits=cfg.vocab.filter(v=>oHas(t,v));if(rep===0)return {passed:true,msg:'Free rep complete.',hits};if(rep===1)return {passed:w<=60&&hits.length>=1,msg:w>60?'Compress further.':hits.length<1?'Use at least one target vocabulary item.':'Compression passed.',hits};if(rep===2){if(kp===0)return {passed:hits.length>=3,msg:hits.length>=3?'Target language passed.':'Use at least three target vocabulary items.',hits};if(kp===1)return {passed:hits.length>=2&&oPurposeCount(t)>=2,msg:oPurposeCount(t)<2?'Use at least two purpose patterns.':hits.length<2?'Use at least two target vocabulary items.':'Target language passed.',hits};return {passed:hits.length>=5,msg:hits.length>=5?'All five target words used.':'Use all five target words.',hits};}if(rep===3)return {passed:w>=8,msg:w>=8?'Reactive rep complete.':'Give a fuller direct response.',hits};if(kp===1)return {passed:w<=55&&hits.length>=2&&oPurposeCount(t)>=1,msg:oPurposeCount(t)<1?'Use one purpose pattern.':hits.length<2?'Use at least two target items.':w>55?'Land it faster.':'Pressure finish passed.',hits};return {passed:w<=55&&hits.length>=(kp===2?3:2),msg:hits.length<(kp===2?3:2)?'Use more target vocabulary.':w>55?'Land it faster.':'Pressure finish passed.',hits};}
function oRubric(r){const sc=x=>{const n=Number(x?.score||0);return n>=1&&n<=3?n:'–';};return `<div><b>Task ${sc(r?.task_achievement)}/3</b> · ${safe(r?.task_achievement?.comment||'')}</div><div><b>Range ${sc(r?.range)}/3</b> · ${safe(r?.range?.comment||'')}</div><div><b>Accuracy ${sc(r?.accuracy)}/3</b> · ${safe(r?.accuracy?.comment||'')}</div><div><b>Flow ${sc(r?.fluency)}/3</b> · ${safe(r?.fluency?.comment||'')}</div><div><b>Coherence ${sc(r?.coherence)}/3</b> · ${safe(r?.coherence?.comment||'')}</div>`;}
const oBaseSend=sendForFeedback;
sendForFeedback=async function(box,prompt,btn){if(box.classList.contains('oracy-vocab-drill'))return oBaseSend(box,prompt,btn);const status=box.querySelector('.status'),feedback=box.querySelector('.feedback');mediaStream?.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});status.textContent='Getting feedback…';try{const form=new FormData();form.append('action','evaluate');form.append('unit','B1 Unit 1');form.append('unit_no',String(UNIT_NO));form.append('prompt',prompt);form.append('audio',blob,'answer.webm');const res=await fetch(EDGE,{method:'POST',body:form});if(!res.ok)throw new Error(await responseError(res,'Feedback'));const data=await res.json(),t=String(data.transcript||''),r=data.rubric||{},kp=Number(box.dataset.kpIndex||0),rep=Number(box.dataset.repIndex||0),c=oConstraint(kp,rep,t);if(c.passed&&rep===2){const ch=oChallenge(kp,t),next=oBox(kp,3),cb=next?.querySelector('.oracy-reactive-challenge'),nb=next?.querySelector('.record');if(cb)cb.innerHTML=`<b>Coach challenge — based on your Rep 3 answer</b><div style="margin-top:5px">${safe(ch)}</div>`;if(nb)nb.dataset.prompt=`${ch} Respond directly in 20 to 30 seconds.`;}if(c.passed&&rep<4)oLock(kp,rep+1,false);feedback.innerHTML=`<b>Coach feedback · Key Point ${kp+1} · Rep ${rep+1}</b><div style="margin-top:8px"><b>${c.passed?'✓ Rep constraint passed':'Rep constraint not met yet'}</b><div>${safe(c.msg)}</div><div><b>Target vocabulary heard:</b> ${safe(c.hits.join(', ')||'none yet')}</div></div><div style="margin-top:12px">${oRubric(r)}</div>`;status.textContent=c.passed?(rep===4?'Five-rep Speaking Gym complete.':`Rep ${rep+1} complete. Rep ${rep+2} unlocked.`):'Try this rep again.';btn.textContent=c.passed?'🎤 Record again':'🎤 Try this rep again';}catch(e){status.textContent=(e.message||'Feedback failed.')+' Recording discarded.';}finally{chunks=[];recorder=null;activeButton=null;btn.classList.remove('live');}};
oBuild();for(let kp=0;kp<3;kp++){oLock(kp,0,false);for(let r=1;r<5;r++)oLock(kp,r,true);}
// Load the separate vocabulary drill layer after the three core speaking gyms exist.
if(!document.querySelector('script[data-oracy-vocab-drills]')){const s=document.createElement('script');s.src='./unit-1-vocab-drills.js?v=20260910';s.dataset.oracyVocabDrills='1';document.body.appendChild(s);}
