// Shared ORACY runtime for Unit 2 onward. Unit-specific language lives in protected unit-N-content.js files.
(function(){
  'use strict';
  const U=window.ORACY_UNIT,EDGE='/oracy/session';
  if(!U)throw new Error('ORACY unit content is missing.');
  const passageStyle='Sound natural, lively and warm. Use clear learner-friendly pacing, expressive sentence stress and natural pitch. In dialogue, react to the other person. Do not sound formal, flat, slow or robotic.';
  const teacherStyle='Speak as a warm, cheerful English teacher. Be specific, calm and encouraging. Say the model sentence clearly, then invite the learner to make a new sentence. Never sound clinical, sugary or robotic.';
  const pronStyle='Speak clearly and naturally for an English listening and pronunciation exercise. Give only the requested word or sentence. Make the target contrast audible without unnatural over-enunciation.';
  const raw=new Map(),pending=new Map(),decoded=new Map();let ctx=null,current=[],rec=null,stream=null,chunks=[],active=null;

  function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function norm(v){return String(v||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim();}
  function audioContext(){if(ctx)return ctx;const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error('Audio is not supported in this browser.');ctx=new C();return ctx;}
  async function unlock(){const c=audioContext();if(c.state!=='running')await c.resume();return c;}
  function stop(){current.forEach(s=>{try{s.stop();}catch{}});current=[];}
  async function fetchRaw(text,voice,style,key){const k=key||`${voice}|${style}|${text}`;if(raw.has(k))return raw.get(k);if(pending.has(k))return pending.get(k);const job=(async()=>{const r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'tts',text,voice,instructions:style,unit_no:U.unitNo,passage_id:key||''})});if(!r.ok)throw new Error(`Audio could not be prepared (HTTP ${r.status}).`);const a=await(await r.blob()).arrayBuffer();raw.set(k,a);return a})();pending.set(k,job);try{return await job}finally{pending.delete(k)}}
  async function getAudio(text,voice='marin',style=teacherStyle,key=''){const k=key||`${voice}|${style}|${text}`;if(decoded.has(k))return decoded.get(k);const a=await fetchRaw(text,voice,style,key);const b=await audioContext().decodeAudioData(a.slice(0));decoded.set(k,b);return b;}
  async function play(buffers,gap=.06){const c=await unlock();stop();let when=c.currentTime+.03;await new Promise(resolve=>{if(!buffers.length)return resolve();const sources=[];buffers.forEach((b,i)=>{const s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start(when);when+=b.duration+gap;sources.push(s);if(i===buffers.length-1)s.onended=resolve});current=sources});current=[];}
  async function say(text,key='',style=teacherStyle){const b=await getAudio(text,'marin',style,key);await play([b],.02);}

  function renderPassages(){document.querySelectorAll('[data-passage]').forEach(box=>{const id=box.dataset.passage,segs=U.passages[id]||[];box.innerHTML=segs.length>1?segs.map(([s,,t])=>`<p><b>${esc(s)}:</b> ${esc(t)}</p>`).join(''):esc(segs.map(x=>x[2]).join(' '));});}
  renderPassages();

  async function playPassage(button){const id=button.dataset.id,segs=U.passages[id]||[],note=button.parentElement.querySelector('.audio-note'),old=button.textContent;try{button.disabled=true;button.textContent='Preparing audio…';const bs=await Promise.all(segs.map(([s,v,t],i)=>getAudio(t,v||'marin',passageStyle,`${U.level.toLowerCase()}-u${U.unitNo}-${id}-${i}-${v||'marin'}-v1`)));button.textContent=segs.length>1?'Playing conversation…':'Playing passage…';await play(bs,segs.length>1?.07:.02);note.textContent='Ready.'}catch(e){note.textContent=e.message||'Audio could not be played.'}finally{button.disabled=false;button.textContent=old}}

  const attempts=new Map();
  function correctLabel(btn){const q=btn.dataset.question,a=btn.dataset.answer;return btn.closest('.activity').querySelector(`input[name="${q}"][value="${a}"]`)?.closest('label')?.textContent.trim()||'';}
  async function check(btn){const box=btn.closest('.activity'),q=btn.dataset.question,chosen=box.querySelector(`input[name="${q}"]:checked`),out=box.querySelector('.answer');if(!chosen){out.className='answer bad';out.textContent='Choose an answer first.';return}if(chosen.value===btn.dataset.answer){attempts.set(q,0);out.className='answer ok';out.innerHTML='<b>Correct. Well done!</b>';say('Correct. Well done!',`${U.level}-u${U.unitNo}-${q}-correct`).catch(()=>{});return}const n=(attempts.get(q)||0)+1;attempts.set(q,n);if(n<2){out.className='answer bad';out.innerHTML='<b>Not quite. Try once more.</b>';say('Not quite. Try once more.',`${U.level}-u${U.unitNo}-${q}-retry`).catch(()=>{});return}const answer=correctLabel(btn),note=U.notes[q]||'';out.className='answer bad';out.innerHTML=`<b>Not quite. The answer is ${esc(answer)}.</b>${note?`<div class="model">${esc(note)}</div>`:''}`;say(`Not quite. The answer is ${answer}. ${note}`,`${U.level}-u${U.unitNo}-${q}-model`).catch(()=>{});attempts.set(q,0);}

  async function playQuestion(button){const id=button.dataset.questionAudio,q=U.oral[id]?.question||'';try{button.disabled=true;await say(q,`${U.level}-u${U.unitNo}-${id}-question`)}finally{button.disabled=false}}
  async function playPron(button){const id=button.dataset.pron,text=U.pron[id];try{button.disabled=true;await say(text,`${U.level}-u${U.unitNo}-${id}-pron`,pronStyle)}finally{button.disabled=false}}

  let oralRec=null,oralStream=null,oralChunks=[],oralButton=null;
  async function oralToggle(button){const id=button.dataset.oral,box=button.closest('.activity'),status=box.querySelector('.status');if(oralRec&&oralButton===button){oralRec.stop();return}if(oralRec){status.textContent='Finish the current recording first.';return}try{oralStream=await navigator.mediaDevices.getUserMedia({audio:true});oralChunks=[];oralButton=button;oralRec=new MediaRecorder(oralStream);oralRec.ondataavailable=e=>{if(e.data.size)oralChunks.push(e.data)};oralRec.onstop=()=>oralCheck(box,button,id);oralRec.start();button.textContent='■ Stop & check';status.textContent='Recording…'}catch{status.textContent='Please allow microphone access.'}}
  async function oralCheck(box,button,id){const spec=U.oral[id],status=box.querySelector('.status'),out=box.querySelector('.answer');oralStream?.getTracks().forEach(t=>t.stop());const blob=new Blob(oralChunks,{type:oralRec?.mimeType||'audio/webm'});status.textContent='Checking your answer…';try{const prompt=`Short spoken comprehension check. Question: ${spec.question}\n${spec.key}\nScore task achievement 3 only if the required factual content is present, 2 if partly correct, and 1 if wrong or off-topic. Keep the other CEFR-aligned dimensions, but do not demand discourse markers here.`;const form=new FormData();form.append('action','evaluate');form.append('unit',`TELW Level ${U.level} Unit ${U.unitNo}`);form.append('unit_no',String(U.unitNo));form.append('prompt',prompt);form.append('audio',blob,'answer.webm');const r=await fetch(EDGE,{method:'POST',body:form});if(!r.ok)throw new Error('Answer check could not be completed.');const d=await r.json(),score=Number(d?.rubric?.task_achievement?.score||0);if(score===3){attempts.set(id,0);out.className='answer ok';out.innerHTML='<b>Correct. Well done!</b>';status.textContent='Your recording was checked and discarded.';await say('Correct. Well done!',`${U.level}-u${U.unitNo}-${id}-oral-ok`)}else{const n=(attempts.get(id)||0)+1;attempts.set(id,n);if(n<2){out.className='answer bad';out.innerHTML='<b>Not quite. Try once more.</b>';status.textContent='Listen to the question and try again.';await say('Not quite. Listen to the question and try once more.',`${U.level}-u${U.unitNo}-${id}-oral-retry`)}else{out.className='answer bad';out.innerHTML=`<b>Try this first:</b><div class="model">${esc(spec.expected)}</div><b>Now answer again in your own words.</b>`;status.textContent='Use the model, then record your own answer.';await say(`Try this first. ${spec.expected} Now answer again in your own words.`,`${U.level}-u${U.unitNo}-${id}-oral-model`);attempts.set(id,0)}}}catch(e){status.textContent=e.message||'Answer check could not be completed.'}finally{oralChunks=[];oralRec=null;oralButton=null;button.textContent='🎤 Record answer'}}

  let pronRec=null,pronStream=null,pronChunks=[];
  async function pronRecord(button){const box=button.closest('.activity'),status=box.querySelector('.status');if(pronRec){pronRec.stop();return}try{pronStream=await navigator.mediaDevices.getUserMedia({audio:true});pronChunks=[];pronRec=new MediaRecorder(pronStream);pronRec.ondataavailable=e=>{if(e.data.size)pronChunks.push(e.data)};pronRec.onstop=()=>{pronStream?.getTracks().forEach(t=>t.stop());const blob=new Blob(pronChunks,{type:pronRec?.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);let replay=box.querySelector('.self-playback');if(!replay){replay=document.createElement('button');replay.className='self-playback';replay.type='button';box.appendChild(replay)}replay.textContent='▶ Play my recording';replay.onclick=()=>new Audio(url).play().catch(()=>{});status.textContent='Good. Hear the model again, then compare it with your recording.';button.textContent='🎤 Record again';pronRec=null};pronRec.start();button.textContent='■ Stop recording';status.textContent='Recording…'}catch{status.textContent='Please allow microphone access.'}}

  function markerGuide(box,spec){if(!spec.min)return;const labels=spec.markers.map(x=>x==='by the way'?'By the way':x==='you know what'?'You know what?':x[0].toUpperCase()+x.slice(1));const div=document.createElement('div');div.className='marker-guide';div.innerHTML=`<b>Make the reply sound natural.</b><br>Use at least ${spec.min}: <b>${esc(labels.join(' · '))}</b>`;box.insertBefore(div,box.querySelector('.record'));}
  function modelBlock(spec){return `<div class="model"><b>Try this first:</b> “${esc(spec.model)}”<br><b>Now you:</b> ${esc(spec.own)}</div>`;}
  function score(x){const n=Number(x?.score||0);return n>=1&&n<=3?n:'–';}
  function feedbackHtml(r,spec,used){const task=score(r.task_achievement),range=score(r.range),accuracy=score(r.accuracy),fluency=score(r.fluency),coherence=score(r.coherence),phon=score(r.phonological_control);return `<b>Coach feedback</b><div style="height:8px"></div><div><b>Did you complete the task? ${task}/3</b><br>${task===3?'Yes. Now make one detail more vivid.':'Cover every part, one short sentence at a time.'}${modelBlock(spec)}</div><div><b>Your words and expressions ${range}/3</b><br>${used.length?`Good: you used ${esc(used.join(', '))}.`:'Bring one Unit 2 phrase into your next answer.'}${modelBlock(spec)}</div><div><b>Your sentences ${accuracy}/3</b><br>Keep the request shape clean: <i>Could you + verb…?</i> or <i>Do you mind if I + verb…?</i></div><div><b>Your flow ${fluency}/3</b><br>Say the request as one small chunk. Pause. Then give the reason or reply.</div><div><b>Easy to follow? ${coherence}/3</b><br>Put the favour first, then the reason, then the return time.</div><div><b>Pronunciation and voice ${phon}/3</b><br>The evaluator may judge broad intelligibility from audio. Use the Unit 2 listening practice for fine /θ/ and /ð/ work; transcript alone cannot prove those sounds.</div>`;}
  async function speakFeedback(box,text){let replay=box.querySelector('.oracy-hear-feedback');if(!replay){replay=document.createElement('button');replay.type='button';replay.className='oracy-hear-feedback';box.querySelector('.feedback').appendChild(replay)}replay.disabled=true;replay.textContent='🔊 Preparing teacher feedback…';try{const b=await getAudio(text,'marin',teacherStyle,`${U.level}-u${U.unitNo}-feedback-${Date.now()}`);replay.disabled=false;replay.textContent='🔊 Hear teacher feedback again';replay.onclick=()=>play([b],.02);await play([b],.02)}catch{replay.disabled=false;replay.textContent='🔊 Try teacher feedback audio again';replay.onclick=()=>speakFeedback(box,text)}}
  async function speakToggle(button){const box=button.closest('.speak'),status=box.querySelector('.status');if(rec&&active===button){rec.stop();return}if(rec){status.textContent='Finish the current recording first.';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];active=button;rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>sendSpeaking(box,button);rec.start();button.textContent='■ Stop & get feedback';button.classList.add('live');status.textContent='Recording…'}catch{status.textContent='Please allow microphone access.'}}
  async function sendSpeaking(box,button){const id=button.dataset.task,spec=U.speaking[id],status=box.querySelector('.status'),feedback=box.querySelector('.feedback');stream?.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec?.mimeType||'audio/webm'});status.textContent='Getting feedback…';try{const prompt=`Speaking task: ${spec.prompt}\nEvaluate with the existing CEFR-aligned dimensions: Task achievement, Range, Accuracy, Fluency, Coherence and Phonological control. Learner-facing feedback must be warm, simple and practical. Fine pronunciation must not be inferred from transcript alone. Target language: ${(U.targets||[]).join(', ')}.`;const form=new FormData();form.append('action','evaluate');form.append('unit',`TELW Level ${U.level} Unit ${U.unitNo}`);form.append('unit_no',String(U.unitNo));form.append('prompt',prompt);form.append('audio',blob,'answer.webm');const r=await fetch(EDGE,{method:'POST',body:form});if(!r.ok)throw new Error('Feedback could not be completed.');const d=await r.json(),rubric=d.rubric||{},t=norm(d.transcript),used=spec.markers.filter(m=>t.includes(norm(m))),passed=used.length>=spec.min;feedback.innerHTML=feedbackHtml(rubric,spec,used)+(passed?'':`<div class="model"><b>One more try:</b> Use at least one suitable response such as “Certainly” or “Of course”, then record again.</div>`);const voice=`Good effort. Try this first. ${spec.model} Now use that model and make one of your own. ${passed?'Your conversational response sounded natural.':'On your next recording, add one warm response such as Certainly or Of course.'}`;await speakFeedback(box,voice);status.textContent=passed?'Recording checked and discarded.':'Try again with one suitable warm response.';button.textContent=passed?'🎤 Record again':'🎤 Try again'}catch(e){status.textContent=(e.message||'Feedback could not be completed.')+' Your recording was discarded.'}finally{chunks=[];rec=null;active=null;button.classList.remove('live')}}

  document.querySelectorAll('.audio').forEach(b=>b.addEventListener('click',()=>playPassage(b)));
  document.querySelectorAll('.check').forEach(b=>b.addEventListener('click',()=>check(b)));
  document.querySelectorAll('.hear-question').forEach(b=>b.addEventListener('click',()=>playQuestion(b)));
  document.querySelectorAll('.hear-pron').forEach(b=>b.addEventListener('click',()=>playPron(b)));
  document.querySelectorAll('.record-oral').forEach(b=>b.addEventListener('click',()=>oralToggle(b)));
  document.querySelectorAll('.record-pron').forEach(b=>b.addEventListener('click',()=>pronRecord(b)));
  document.querySelectorAll('.record').forEach(b=>{if(b.closest('[data-ai-conversation]'))return;const box=b.closest('.speak'),spec=U.speaking[b.dataset.task];markerGuide(box,spec);b.addEventListener('click',()=>speakToggle(b))});
  document.addEventListener('pointerdown',e=>{if(e.target.closest('button'))unlock().catch(()=>{})},{capture:true,passive:true});

  async function preload(){const fast=[];document.querySelectorAll('.hear-question').forEach(b=>{const id=b.dataset.questionAudio;fast.push(()=>getAudio(U.oral[id].question,'marin',teacherStyle,`${U.level}-u${U.unitNo}-${id}-question`))});document.querySelectorAll('.hear-pron').forEach(b=>{const id=b.dataset.pron;fast.push(()=>getAudio(U.pron[id],'marin',pronStyle,`${U.level}-u${U.unitNo}-${id}-pron`))});let i=0;async function worker(){while(i<fast.length){try{await fast[i++]()}catch{}}}await Promise.all(Array.from({length:Math.min(6,fast.length)},worker));for(const [id,segs] of Object.entries(U.passages))segs.forEach(([s,v,t],n)=>fetchRaw(t,v||'marin',passageStyle,`${U.level.toLowerCase()}-u${U.unitNo}-${id}-${n}-${v||'marin'}-v1`).catch(()=>{}));}
  setTimeout(()=>preload().catch(()=>{}),0);
})();
