(function(){
'use strict';
const U=window.ORACY_UNIT;if(!U||Number(U.unitNo)!==61)return;
const B=[
{w:[
['formative','having a strong influence on a person’s development','Those formative years shaped the way she understood community.'],
['pivotal','extremely important because it changes what happens next','Being asked to lead the project was a pivotal moment in his career.'],
['trajectory','the direction in which a life or career develops','That internship changed the trajectory of her career.'],
['vocation','work that a person feels especially suited or committed to','He gradually realised that teaching was his vocation.'],
['resilience','the ability to recover and continue after difficulty','Her resilience became clear when she rebuilt the programme after its funding was withdrawn.']],
i:[
['find your feet','become confident and comfortable in a new situation','It took her a few months to find her feet in broadcasting.'],
['carve out a niche','create a specialised area in which you become successful','He carved out a niche by reporting complex science in clear language.'],
['come full circle','return to something connected with where you began, now with a new understanding','Her career came full circle when she returned to her old college as its director.']],
u:'In Speaking 1 and Speaking 2, use at least two words and one idiomatic expression from this bank.'},
{w:[
['presume','believe something is probably true without having complete proof','I had presumed that Dr Shah studied medicine, but I may have that wrong.'],
['clarify','make an idea or piece of information clearer and more exact','Could I clarify one detail? I studied economics, not finance.'],
['tactful','careful not to embarrass, upset or offend another person','Her correction was tactful: she fixed the detail without making him feel foolish.'],
['misconception','an incorrect belief caused by misunderstanding','There is a common misconception that he inherited the business.'],
['inference','a conclusion reached from the information available','That was a reasonable inference, although it was not correct.']],
i:[
['put two and two together','use separate facts to reach a conclusion','I saw your Edinburgh address and put two and two together, but I reached the wrong conclusion.'],
['get the wrong end of the stick','misunderstand a situation or what somebody meant','I am afraid I got the wrong end of the stick about your first degree.'],
['set the record straight','correct a false idea by giving the true facts','Let me set the record straight: I joined the company after university, not before it.']],
u:'In Speaking 3 and Speaking 4, use at least two words and one idiomatic expression from this bank.'},
{w:[
['adversity','a difficult situation that tests a person','The profile shows how she responded to adversity without making her sound heroic.'],
['recognition','public acknowledgement that someone or something is valuable or successful','Her research received international recognition several years later.'],
['initiative','a new plan or action intended to solve a problem','She launched an initiative that brought designers and older users together.'],
['transition','the process of changing from one state, role or stage to another','His transition from engineering to education took several years.'],
['legacy','the lasting effect that a person’s work or life leaves behind','Her real legacy is the expectation that users should be involved from the beginning.']],
i:[
['a turning point','an event that causes an important change in direction','Getting laid off became a turning point rather than the end of her career.'],
['against the odds','despite serious difficulties that made success unlikely','Against the odds, the small workshop survived and attracted national attention.'],
['go from strength to strength','become increasingly successful or effective','Once the first design was approved, the organisation went from strength to strength.']],
u:'In Speaking 5, use at least two words and one idiomatic expression from this bank.'}
];
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let serial=0;B.forEach(x=>[...x.w,...x.i].forEach(y=>{const id='u61-v-'+serial++;U.pron[id]=y[2];if(!U.targets.includes(y[0]))U.targets.push(y[0])}));
function card(x,type,id){return `<article class="u61vc"><div class="u61vt">${type}</div><h4>${esc(x[0])}</h4><p><b>Meaning:</b> ${esc(x[1])}</p><p><b>My sentence:</b> “${esc(x[2])}”</p><button type="button" class="hear-pron" data-pron="u61-v-${id}">🔊 Hear my sentence</button><div class="u61own"><p><b>Now make your own sentence.</b> Use “${esc(x[0])}”, record it, and get feedback. You may make one improved attempt if needed.</p><button type="button" class="u61record" data-attempt="0" data-term="${esc(x[0])}" data-meaning="${esc(x[1])}">🎤 Record your sentence</button><div class="status" aria-live="polite"></div><div class="feedback"></div></div></article>`}
function panel(k,offset){const x=B[k],e=document.createElement('section');e.className='u61v';e.innerHTML=`<div class="eyebrow">Vocabulary building · Key Point ${k+1}</div><h3>Hear it. Then make it yours.</h3><p>Listen to each model sentence. Then make and record one sentence of your own.</p><div class="u61sub"><b>Five core words</b></div><div class="u61grid">${x.w.map((y,i)=>card(y,'Core word',offset+i)).join('')}</div><div class="u61sub"><b>Three idiomatic expressions</b></div><div class="u61grid">${x.i.map((y,i)=>card(y,'Idiomatic expression',offset+5+i)).join('')}</div><p class="u61return"><b>Now return to speaking:</b> ${esc(x.u)}</p>`;return e}
const secs=[...document.querySelectorAll('section.kp')].slice(0,3);let offset=0;secs.forEach((s,k)=>{const p=panel(k,offset);offset+=8;const listen=[...s.children].find(x=>x.tagName==='H3'&&x.textContent.startsWith('Listen:'));listen?s.insertBefore(p,listen):s.appendChild(p);const first=s.querySelector('.speak');if(first){const c=document.createElement('div');c.className='marker-guide u61use';c.innerHTML=`<b>Vocabulary use target</b><br>${esc(B[k].u)}`;first.before(c)}});
let rec=null,stream=null,chunks=[],active=null;
const norm=v=>String(v||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim();
async function toggleRecord(btn){const box=btn.closest('.u61own'),status=box.querySelector('.status');if(Number(btn.dataset.attempt||0)>=2){status.textContent='Two attempts completed for this expression.';return}if(rec&&active===btn){rec.stop();return}if(rec){status.textContent='Finish the current recording first.';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];active=btn;rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>checkUsage(btn,box);rec.start();btn.textContent='■ Stop and get feedback';status.textContent=`Recording Attempt ${Number(btn.dataset.attempt||0)+1} of 2…`}catch{status.textContent='Please allow microphone access.'}}
async function checkUsage(btn,box){const term=btn.dataset.term,meaning=btn.dataset.meaning,attempt=Number(btn.dataset.attempt||0)+1,status=box.querySelector('.status'),feedback=box.querySelector('.feedback'),blob=new Blob(chunks,{type:rec?.mimeType||'audio/webm'});stream?.getTracks().forEach(t=>t.stop());status.textContent='Checking your sentence…';btn.disabled=true;try{const form=new FormData();form.append('action','evaluate');form.append('unit','TELW Level D1A Unit 1 vocabulary');form.append('unit_no','61');form.append('prompt',`The learner must make one original spoken sentence using “${term}” in this sense: ${meaning}. Decide whether the expression is present, its meaning fits, and the sentence is natural. If all three are correct, say only “Good.” Otherwise give one short, specific correction and one concise improved model. This is attempt ${attempt} of 2.${attempt===1?' Allow one final improved attempt only if correction is needed.':' Do not invite another attempt.'}`);form.append('audio',blob,'usage.webm');const r=await fetch('/oracy/session',{method:'POST',body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.message||'Feedback could not be prepared.');btn.dataset.attempt=String(attempt);const heard=norm(d.transcript).includes(norm(term)),achievement=Number(d.rubric?.task_achievement?.score||0),accuracy=Number(d.rubric?.accuracy?.score||0),correct=heard&&achievement>=2&&accuracy>=2;if(correct){feedback.innerHTML='<b>Good.</b>';status.textContent='Sentence complete.';btn.textContent='✓ Complete';btn.dataset.attempt='2'}else{const correction=d.rubric?.accuracy?.comment||d.rubric?.task_achievement?.comment||`Use “${term}” once in a natural sentence with the meaning shown above.`,model=d.rubric?.improved_version||d.improved_version||`Make one clear sentence of your own using “${term}”.`;feedback.innerHTML=`<b>Try this:</b> ${esc(correction)}<div class="model"><b>Improved model:</b> “${esc(model)}”</div>`;if(attempt===1){status.textContent='You may make one improved attempt.';btn.textContent='🎤 Record your improved sentence'}else{status.textContent='Final feedback.';btn.textContent='✓ Complete'}}}catch(e){status.textContent=(e.message||'Feedback could not be prepared.')+' This failed check has not used an attempt.';btn.textContent=attempt===1?'🎤 Record your sentence':'🎤 Record your improved sentence'}finally{chunks=[];rec=null;stream=null;active=null;btn.disabled=Number(btn.dataset.attempt||0)>=2}}
document.querySelectorAll('.u61record').forEach(btn=>btn.addEventListener('click',()=>toggleRecord(btn)));
const st=document.createElement('style');st.textContent='.u61v{margin:22px 0;padding:18px;border:1px solid #d7e2ea;border-radius:14px;background:#f8fbfd}.u61v>h3{margin:7px 0}.u61sub{margin:18px 0 9px}.u61grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.u61vc{padding:13px;border:1px solid #dce5eb;border-radius:11px;background:#fff}.u61vc h4{margin:4px 0 8px;font-size:18px}.u61vc p{margin:6px 0;line-height:1.5}.u61vt{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#7a5a16}.u61own{margin-top:11px;padding-top:10px;border-top:1px solid #e2e9ee}.u61own .feedback>div{margin-top:8px;line-height:1.45}.u61return{margin:16px 0 0;padding:12px;border-radius:9px;background:#fff8e8}@media(max-width:680px){.u61grid{grid-template-columns:1fr}}';document.head.appendChild(st);
})();
