const ACCESS='https://vtqatrhwfvzyodiftvkc.supabase.co/functions/v1/clarion-product-access';
const FIIB='https://vtqatrhwfvzyodiftvkc.supabase.co/functions/v1/fiib-tool-access';
const KEY='sb_publishable_IJJ9AW79DhOsWlsPK_8pkg_q5Fh7643';
export async function onRequest(context){const url=new URL(context.request.url),path=url.pathname;const guarded=/^\/module-\d+-\d+(?:\.html)?$/.test(path)||path.startsWith('/audio/');if(!guarded)return context.next();const c=context.request.headers.get('cookie')||'',paid=read(c,'clarion_product_token');if(paid&&await paidAccess(paid))return secure(await context.next());const fiib=read(c,'pcl_fiib_session'),device=read(c,'pcl_device_id');if(fiib&&device&&await fiibAccess(fiib,device))return secure(await context.next());const admin=read(c,'pcl_admin_session');if(admin&&await adminAccess(admin))return secure(await context.next());return Response.redirect('https://clarionprep.com/subscribe/?product=PCL&next='+encodeURIComponent(path+url.search),302)}
function read(h,n){const m=h.match(new RegExp('(?:^|;\\s*)'+n+'=([^;]+)'));return m?decodeURIComponent(m[1]):''}
async function paidAccess(token){try{const r=await fetch(ACCESS,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify({action:'CHECK',product_code:'PCL'})}),d=await r.json();return r.ok&&d.ok===true}catch{return false}}
async function fiibAccess(token,device){try{const r=await fetch(FIIB,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({action:'CHECK',product_code:'PCL',session_token:token,device_id:device})}),d=await r.json();return r.ok&&d.ok===true}catch{return false}}
async function adminAccess(token){try{const r=await fetch(FIIB,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({action:'ADMIN_CHECK',session_token:token})}),d=await r.json();return r.ok&&d.ok===true}catch{return false}}
function secure(r){const h=new Headers(r.headers);h.set('cache-control','private, no-store, max-age=0');h.set('x-robots-tag','noindex, nofollow, noarchive');return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
