(function(){
'use strict';
function loadXlsx(){return new Promise((res,rej)=>{if(window.XLSX)return res();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=res;s.onerror=()=>rej(Error('Excel reader could not load.'));document.head.appendChild(s)})}
function val(o,names){for(const n of names){const k=Object.keys(o).find(x=>String(x).trim().toLowerCase()===n);if(k&&o[k]!=null)return String(o[k]).trim()}return''}
async function parse(file){await loadXlsx();const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});return rows.map(r=>({roll_number:val(r,['roll number','roll no','roll','student id','studentid']),name:val(r,['name','student name','full name']),email:val(r,['email','email address'])})).filter(r=>r.roll_number||r.email)}
function inject(){if(document.getElementById('piRosterFile'))return;const recipient=document.getElementById('recipientImport');if(!recipient)return;const field=recipient.closest('.field');const box=document.createElement('div');box.className='field full';box.style.marginTop='14px';box.innerHTML='<label for="piRosterFile">Student Excel roster</label><input id="piRosterFile" type="file" accept=".xlsx,.xls,.csv"><div id="piRosterStatus" class="help">Upload the placement roster with the JD. Use columns: Roll Number, Name, Email. Only matched students in this file will receive the PI Lab assignment.</div>';field.parentNode.insertBefore(box,field);recipient.placeholder='Excel roster rows will appear here after upload.';recipient.readOnly=true;
const file=document.getElementById('piRosterFile'),status=document.getElementById('piRosterStatus');file.addEventListener('change',async()=>{try{recipient.value='';if(!file.files[0])return;const rows=await parse(file.files[0]);if(!rows.length)throw Error('No student rows were found. Use Roll Number, Name and Email column headings.');const withoutRoll=rows.filter(r=>!r.roll_number);if(withoutRoll.length)throw Error(withoutRoll.length+' row(s) have no Roll Number. PI release matches by Roll Number.');recipient.value=rows.map(r=>`${r.roll_number} | ${r.name}`).join('\n');recipient.dispatchEvent(new Event('input',{bubbles:true}));status.textContent=rows.length+' student row(s) loaded from '+file.files[0].name+'. Only these matched students will receive this PI Lab set.';}catch(e){status.textContent=e.message}});
const help=field.querySelector('.help');if(help)help.textContent='Roster is populated from the Excel file above. Roll Number is matched to ASCENT and Name is cross-checked. Do not release if Preview matches shows an unmatched student.';
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();