import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const ASCENT_URL='https://vtqatrhwfvzyodiftvkc.supabase.co';
const ASCENT_KEY='sb_publishable_IJJ9AW79DhOsWlsPK_8pkg_q5Fh7643';
const ADMIN_VALIDATE=ASCENT_URL+'/rest/v1/rpc/ascent_admin_trainer_entry_list';
const ALLOWED=new Set(['https://clarionprep.com','https://www.clarionprep.com','https://manuvikraman.com','https://www.manuvikraman.com']);

const UNITS:any={
  31:{internalLevel:'C1A',localUnit:1,title:'Finding Your Voice in a Multilingual Workplace',scenario:'You and the learner are colleagues after a client meeting in an Indian workplace. Discuss what made the communication demanding, what helped, and what the learner will do differently next time.',goals:'Help the learner explain one communication difficulty, respond to a different view, and reach one practical improvement step. Encourage -ing/-ed adjective contrasts, the more... the more..., and since/as for reasons when natural.',language:'overwhelming, articulate, keep up with, settle into, brush up on, open up; confusing/confused, encouraging/encouraged; the more..., the more...; since/as for reasons',model:'The more familiar I am with the topic, the more clearly I speak, since I can focus on the discussion instead of searching for words.'}
};
function cors(req:Request){const o=req.headers.get('origin')||'';return {'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://clarionprep.com','Access-Control-Allow-Headers':'content-type, x-oracy-client','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
function json(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'content-type':'application/json','cache-control':'no-store'}})}
async function sha256(text:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return btoa(String.fromCharCode(...new Uint8Array(b)))}
async function validAdmin(token:string){if(!token)return false;try{const r=await fetch(ADMIN_VALIDATE,{method:'POST',headers:{apikey:ASCENT_KEY,authorization:'Bearer '+ASCENT_KEY,'content-type':'application/json'},body:JSON.stringify({p_session_token:token})});if(!r.ok)return false;const p=await r.json(),x=Array.isArray(p)?p[0]:p;return Boolean(x&&x.ok===true)}catch{return false}}
async function validLearnerUnit(token:string,unitNo:number){if(!token||unitNo<31)return false;const tokenHash=await sha256(token);const {data:s}=await db.from('oracy_sessions').select('learner_id,expires_at,revoked_at').eq('token_hash',tokenHash).maybeSingle();if(!s||s.revoked_at||new Date(s.expires_at).getTime()<=Date.now())return false;const {data:l}=await db.from('oracy_learners').select('id,is_active').eq('id',s.learner_id).maybeSingle();if(!l||l.is_active!==true)return false;const {data:a}=await db.from('oracy_unit_assignments').select('is_active').eq('learner_id',l.id).eq('unit_no',unitNo).maybeSingle();return Boolean(a&&a.is_active===true)}
async function authorised(body:any,unitNo:number){return await validLearnerUnit(String(body?.session_token||''),unitNo)||await validAdmin(String(body?.admin_token||''))}
function instructions(u:any){return `You are the ORACY live spoken-English coach for an adult learner in India. The internal course label is ${u.internalLevel}; it is NOT a CEFR C1 judgement. Keep your language and expectations within the CEFR B range, roughly B1+ to B2.\nScenario: ${u.scenario}\nGoal: ${u.goals}\nRespond directly to what the learner has just said. Sound like a natural adult conversation in UK English. Use one or two short sentences, maximum 30 words. Do not lecture or force target vocabulary. Allow statements as well as questions. Across the exchange, challenge or qualify one learner idea naturally so the learner must react. Useful language when it genuinely fits: ${u.language}. The learner speaks first. Allow exactly four learner turns. After the fourth learner turn, close warmly and do not ask another question. Respond in audio at a natural pace.`}
async function realtimeToken(req:Request,body:any){const unitNo=Number(body?.unit_no||0),u=UNITS[unitNo];if(!u)return json(req,{error:'Live conversation is not available for this Level C unit'},400);if(!(await authorised(body,unitNo)))return json(req,{error:'ORACY access required'},403);const r=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({session:{type:'realtime',model:'gpt-realtime',instructions:instructions(u),audio:{input:{transcription:{model:'gpt-4o-mini-transcribe',language:'en'},turn_detection:{type:'server_vad',threshold:.45,prefix_padding_ms:300,silence_duration_ms:350,create_response:true,interrupt_response:true}},output:{voice:'cedar',speed:1.08}}}})});const d=await r.json().catch(()=>({}));if(!r.ok)return json(req,{error:'Live conversation token failed',detail:String(d?.error?.message||'').slice(0,400)},502);const secret=String(d?.value||d?.client_secret?.value||'');if(!secret)return json(req,{error:'OpenAI did not return a live conversation token'},502);return json(req,{client_secret:secret,expires_at:d?.expires_at||d?.client_secret?.expires_at||null})}
async function conversationFeedback(req:Request,body:any){const unitNo=Number(body?.unit_no||0),u=UNITS[unitNo];if(!u)return json(req,{error:'Conversation feedback is not available for this Level C unit'},400);if(!(await authorised(body,unitNo)))return json(req,{error:'ORACY access required'},403);const raw=Array.isArray(body?.history)?body.history:[],history=raw.slice(-12).map((x:any)=>({role:x?.role==='coach'?'Coach':'Learner',text:String(x?.text||'').slice(0,500)})).filter((x:any)=>x.text);const prompt=`Evaluate this short ORACY conversation. Internal course label: ${u.internalLevel}. IMPORTANT: evaluate at CEFR B-range, not C1/C2. Reward clear meaning, relevant response, workable control of the target structure, suitable vocabulary, coherent interaction and understandable language. Do not penalise the learner for not using an idiom or advanced item when a simpler accurate B-level expression communicates the same meaning.\nTask: ${u.goals}\nUseful unit language: ${u.language}\nTranscript:\n${history.map((x:any)=>x.role+': '+x.text).join('\n')}\nReturn strict JSON with task_achievement, range, accuracy, fluency, coherence, phonological_control, improved_version and next_step. Score the first five 1-3. phonological_control must be {"score":0,"comment":"Not reliably assessed from transcript alone."}. Keep comments warm, concrete and learner-facing. The improved version must preserve the learner's meaning and stay within natural CEFR B-range English.`;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-4o-mini',temperature:.1,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});if(!r.ok)return json(req,{error:'Conversation feedback failed',detail:(await r.text()).slice(0,400)},502);let rubric:any={};try{rubric=JSON.parse((await r.json())?.choices?.[0]?.message?.content||'{}')}catch{}rubric.phonological_control={score:0,comment:'Not reliably assessed from transcript alone.'};rubric.improved_version=String(rubric.improved_version||u.model).slice(0,500);rubric.next_step=String(rubric.next_step||'Keep the same idea, change the situation, and say it again in your own words.').slice(0,500);return json(req,{rubric})}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{error:'POST required'},405);try{const body=await req.json();if(body?.action==='realtime-token')return realtimeToken(req,body);if(body?.action==='conversation-feedback')return conversationFeedback(req,body);return json(req,{error:'Unsupported action'},400)}catch(e){return json(req,{error:'Request failed',detail:String(e?.message||e).slice(0,300)},400)}});
