const app=document.getElementById('app'),restartBtn=document.getElementById('restartBtn'),globalTimer=document.getElementById('globalTimer');
const STORE='ctf60',TOTAL=3600000,PHASE={core:1800000,track:600000,'writing-email':360000,'writing-rec':240000,'writing-revise':120000,workstyle:480000};
const CORE=[...CORE_QUESTIONS,...EXTRA_CORE_QUESTIONS];
const LABEL={verbal:'Verbal reasoning',numerical:'Numerical reasoning',data:'Data interpretation',structured:'Structured problem solving',critical:'Critical thinking',judgement:'Judgement & prioritisation',communication:'Communication clarity',adaptability:'Learning agility'};
const SCALE=['Strongly disagree','Disagree','Neutral / unsure','Agree','Strongly agree'];
let timer=null,state={track:null,phase:'welcome',index:0,answers:{},writing:{email:'',recommendation:'',revision:''},workstyle:{},startedAt:null,phaseStartedAt:null,submitted:false,timedOut:false};
const save=()=>sessionStorage.setItem(STORE,JSON.stringify(state));
const words=s=>String(s||'').trim()?String(s).trim().split(/\s+/).length:0;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmt=ms=>{const s=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const totalLeft=()=>TOTAL-(Date.now()-state.startedAt),phaseLeft=()=>PHASE[state.phase]-(Date.now()-state.phaseStartedAt);
function stop(){if(timer)clearInterval(timer);timer=null}
function tick(){if(!state.startedAt||state.submitted)return;const t=totalLeft();globalTimer.textContent=fmt(t);globalTimer.classList.toggle('danger',t<=300000);const e=document.getElementById('sectionTimer');if(e)e.textContent=fmt(phaseLeft());if(t<=0)return submit(true);if(PHASE[state.phase]&&phaseLeft()<=0)advance(true)}
function runTimer(){stop();globalTimer.classList.remove('hidden');tick();timer=setInterval(tick,500)}
function header(label){return `<div class="time-strip"><div><strong>${label}</strong><span>Section time left: <b id="sectionTimer">${fmt(phaseLeft())}</b></span></div><div><span>Total time left</span><strong>${fmt(totalLeft())}</strong></div></div>`}
function restore(){try{const s=JSON.parse(sessionStorage.getItem(STORE)||'null');if(s?.track)state={...state,...s}}catch{}}
function reset(){sessionStorage.removeItem(STORE);stop();state={track:null,phase:'welcome',index:0,answers:{},writing:{email:'',recommendation:'',revision:''},workstyle:{},startedAt:null,phaseStartedAt:null,submitted:false,timedOut:false};globalTimer.classList.add('hidden');restartBtn.classList.add('hidden');welcome()}
restartBtn.onclick=()=>{if(state.submitted&&confirm('Start a new assessment? This clears the current result.'))reset()};
function welcome(){app.innerHTML='';app.appendChild(document.getElementById('welcomeTemplate').content.cloneNode(true));document.getElementById('beginBtn').onclick=tracks}
function tracks(){app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">Before the clock starts</span><h2>Choose the career track you are targeting</h2><p>Your 60-minute assessment starts immediately after you choose.</p></div></div><div class="track-grid" id="tracks"></div></section>`;const g=document.getElementById('tracks');TRACKS.forEach(t=>{const b=document.createElement('button');b.className='track';b.innerHTML=`<div class="track-title">${t.name}</div><div class="track-family">${t.family}</div>`;b.onclick=()=>start(t);g.appendChild(b)})}
function start(track){state.track=track;state.phase='core';state.index=0;state.answers={};state.writing={email:'',recommendation:'',revision:''};state.workstyle={};state.startedAt=state.phaseStartedAt=Date.now();state.submitted=false;state.timedOut=false;save();runTimer();render()}
function beginPhase(p){state.phase=p;state.index=0;state.phaseStartedAt=Date.now();save();render()}
function qs(){return state.phase==='core'?CORE:[...(FAMILY_MODULES[state.track.family]||[]),...(EXTRA_FAMILY_MODULES[state.track.family]||[])].map((q,i)=>({...q,id:q.id||`tm${i+1}`}))}
function render(){if(state.submitted)return results();if(state.phase==='core'||state.phase==='track')mcq();else if(state.phase.startsWith('writing-'))writing();else workstyle()}
function mcq(){const a=qs(),q=a[state.index],k=`${state.phase}:${q.id}`,ans=state.answers[k],label=state.phase==='core'?'Common Core · 30 minutes':`${state.track.name} module · 10 minutes`;app.innerHTML=`${header(label)}<div class="progress-wrap"><div class="progress-label"><span>${LABEL[q.cap]}</span><span>${state.index+1} of ${a.length}</span></div><div class="progress"><div style="width:${Math.round(state.index/a.length*100)}%"></div></div></div><section class="card question-card"><div class="question-number">${LABEL[q.cap]}</div><div class="question-text">${q.q}</div>${q.ctx?`<div class="context">${q.ctx}</div>`:''}<div id="opts" class="options"></div><div class="nav-row"><button id="back" class="secondary" ${state.index===0?'disabled':''}>Back</button><button id="next" class="primary" ${ans===undefined?'disabled':''}>${state.index===a.length-1?'Finish section':'Next'}</button></div></section>`;const o=document.getElementById('opts');q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='option'+(ans===i?' selected':'');b.innerHTML=`<span class="option-key">${String.fromCharCode(65+i)}</span><span>${x}</span>`;b.onclick=()=>{state.answers[k]=i;save();mcq()};o.appendChild(b)});document.getElementById('back').onclick=()=>{state.index--;save();mcq()};document.getElementById('next').onclick=()=>{if(state.index<a.length-1){state.index++;save();mcq()}else advance(false)}}
function wcfg(){if(state.phase==='writing-email')return [WRITING_TASKS.email,'email','Communication · Task 1 · TELW 1.0','6 minutes · Point → Reason → Example → next step'];if(state.phase==='writing-rec')return [WRITING_TASKS.recommendation,'recommendation','Communication · Task 2A · TELW 2.0','4 minutes · initial recommendation'];return [WRITING_TASKS.revision,'revision','Communication · Task 2B · TELW 2.0','2 minutes · adapt to new evidence']}
function writing(){const [c,k,label,hint]=wcfg(),v=state.writing[k]||'';app.innerHTML=`${header(label)}<section class="card writing-card"><span class="eyebrow">${hint}</span><h2>${c.title}</h2>${c.newFact?`<div class="new-fact"><strong>${c.newFact}</strong></div>`:''}<div class="context">${c.prompt}</div><textarea id="box" class="writing-box" spellcheck="true">${esc(v)}</textarea><div class="writing-meta"><span id="wc">${words(v)} words</span><span>Target: ${c.min}–${c.max}</span></div><div class="nav-row"><span class="fineprint">Saved automatically. This section closes at 00:00.</span><button id="cont" class="primary">Continue</button></div></section>`;const b=document.getElementById('box');b.oninput=()=>{state.writing[k]=b.value;document.getElementById('wc').textContent=`${words(b.value)} words`;save()};document.getElementById('cont').onclick=()=>{state.writing[k]=b.value;save();advance(false)}}
function workstyle(){const q=WORKSTYLE_ITEMS[state.index],ans=state.workstyle[q.id];app.innerHTML=`${header('Work-style alignment · 8 minutes')}<div class="progress-wrap"><div class="progress-label"><span>No right or wrong answer</span><span>${state.index+1} of ${WORKSTYLE_ITEMS.length}</span></div><div class="progress"><div style="width:${Math.round(state.index/WORKSTYLE_ITEMS.length*100)}%"></div></div></div><section class="card question-card"><div class="question-text">${q.text}</div><div id="likert" class="options"></div><div class="nav-row"><button id="back" class="secondary" ${state.index===0?'disabled':''}>Back</button><button id="next" class="primary" ${ans===undefined?'disabled':''}>${state.index===WORKSTYLE_ITEMS.length-1?'Submit assessment':'Next'}</button></div></section>`;const g=document.getElementById('likert');SCALE.forEach((x,i)=>{const n=i+1,b=document.createElement('button');b.className='option'+(ans===n?' selected':'');b.innerHTML=`<span class="option-key">${n}</span><span>${x}</span>`;b.onclick=()=>{state.workstyle[q.id]=n;save();workstyle()};g.appendChild(b)});document.getElementById('back').onclick=()=>{state.index--;save();workstyle()};document.getElementById('next').onclick=()=>{if(state.index<WORKSTYLE_ITEMS.length-1){state.index++;save();workstyle()}else submit(false)}}
function advance(){if(state.phase==='core')beginPhase('track');else if(state.phase==='track')beginPhase('writing-email');else if(state.phase==='writing-email')beginPhase('writing-rec');else if(state.phase==='writing-rec')beginPhase('writing-revise');else if(state.phase==='writing-revise')beginPhase('workstyle');else submit(false)}
function submit(to){if(state.submitted)return;state.submitted=true;state.timedOut=!!to;save();stop();globalTimer.textContent=to?'00:00':fmt(Math.max(0,totalLeft()));restartBtn.classList.remove('hidden');results()}
function scoreQ(a,p){let c=0,caps={};a.forEach(q=>{if(!caps[q.cap])caps[q.cap]={c:0,t:0};caps[q.cap].t++;if(state.answers[`${p}:${q.id}`]===q.a){c++;caps[q.cap].c++}});return {score:Math.round(c/a.length*100),caps}}
const any=(s,r)=>r.test(String(s||'').toLowerCase()),rng=(n,a,b)=>n>=a&&n<=b?20:n>=a*.75&&n<=b*1.25?12:n?6:0;
function emailScore(s){let x=rng(words(s),80,140);if(any(s,/because|due to|since|reason/))x+=15;if(/\d/.test(s))x+=15;if(any(s,/will|please|confirm|next step|monday|friday|send/))x+=20;if((s.match(/\n/g)||[]).length)x+=10;if(any(s,/dear|hello|hi /))x+=10;if(any(s,/regards|sincerely|thank you|thanks/))x+=10;return Math.min(100,x)}
function recScore(s){let x=rng(words(s),90,150);if(any(s,/recommend|propose|suggest/))x+=20;if(/42|6 lakh|4.?7|complaint|waiting/.test(s.toLowerCase()))x+=20;if(any(s,/because|therefore|given/))x+=15;if(any(s,/pilot|test|track|measure|monitor|next step/))x+=20;if((s.match(/\n/g)||[]).length)x+=5;return Math.min(100,x)}
function revScore(s){let x=rng(words(s),60,120);if(/35|40%|incorrect information|wrong information/.test(s.toLowerCase()))x+=25;if(any(s,/however|given|new information|now|change|instead/))x+=20;if(any(s,/recommend|propose|suggest/))x+=15;if(any(s,/pilot|test|train|measure|monitor|check/))x+=20;return Math.min(100,x)}
function workScore(){let traits={};WORKSTYLE_ITEMS.forEach(i=>{(traits[i.trait]??=[]);if(state.workstyle[i.id])traits[i.trait].push(+state.workstyle[i.id])});let s=0,n=0;Object.entries(WORKSTYLE_PROFILES[state.track.family]||{}).forEach(([t,target])=>{if(!traits[t]?.length)return;const a=traits[t].reduce((x,y)=>x+y,0)/traits[t].length;s+=Math.max(0,100-Math.abs(a-target)*25);n++});return n?Math.round(s/n):0}
function results(){const tq=qsForTrack(),c=scoreQ(CORE,'core'),t=scoreQ(tq,'track'),caps={};Object.keys(LABEL).forEach(k=>{const a=c.caps[k]||{c:0,t:0},b=t.caps[k]||{c:0,t:0},d=a.t+b.t*1.5;caps[k]=d?Math.round((a.c+b.c*1.5)/d*100):0});const e=emailScore(state.writing.email),r=recScore(state.writing.recommendation),v=revScore(state.writing.revision),comm=Math.round((e+(r*.6+v*.4))/2),ws=workScore(),overall=Math.round(c.score*.45+t.score*.25+comm*.2+ws*.1),st=overall>=78?['Strong current fit','good']:overall>=62?['Promising — development needed','warn']:['Low current readiness','bad'];const ordered=Object.entries(caps).sort((a,b)=>b[1]-a[1]),gaps=ordered.slice(-3).reverse(),training=gaps.map(([k,s])=>({k,s,...TRAINING[k]}));app.innerHTML=`<section class="card"><div class="results-hero"><div><span class="status ${st[1]}">${st[0]}</span><h2>${state.track.name}</h2><p class="lead">Overall readiness: <strong>${overall}/100</strong></p>${state.timedOut?'<div class="new-fact"><strong>Time expired at 60:00. The assessment was submitted automatically.</strong></div>':''}<p>This is a developmental placement-readiness diagnostic, not a validated psychometric test or guarantee of placement success.</p></div><div class="score-ring" style="--score:${overall}"><div class="inside"><strong>${overall}</strong><span>readiness</span></div></div></div><div class="component-grid"><div><span>Core</span><strong>${c.score}</strong><small>45%</small></div><div><span>Track</span><strong>${t.score}</strong><small>25%</small></div><div><span>Communication</span><strong>${comm}</strong><small>20%</small></div><div><span>Work-style</span><strong>${ws}</strong><small>10%</small></div></div><div class="metric-grid">${Object.entries(caps).map(([k,s])=>`<div class="metric"><div class="metric-head"><span>${LABEL[k]}</span><span>${s}</span></div><div class="bar"><div style="width:${s}%"></div></div></div>`).join('')}</div></section><div class="results-grid"><section class="result-card"><h3>Communication structure</h3><ul><li><strong>TELW 1.0 email:</strong> ${e}/100</li><li><strong>TELW 2.0 initial recommendation:</strong> ${r}/100</li><li><strong>TELW 2.0 revision after new evidence:</strong> ${v}/100</li></ul><p class="fineprint">Automated structural score; human review is still needed for nuance, grammar and judgement.</p></section><section class="result-card training"><h3>Recommended training path</h3>${training.map((x,i)=>`<div class="training-item"><div class="training-icon">${i+1}</div><div><div class="training-title">${x.title}</div><div class="training-desc">${x.desc}</div></div><span class="training-tag">Priority ${i+1}</span></div>`).join('')}</section></div><div class="nav-row"><span class="fineprint">40 core questions · 12 track questions · 2 writing tasks / 3 responses · 16 work-style items</span><button id="print" class="primary">Print / Save result</button></div>`;document.getElementById('print').onclick=()=>window.print()}
function qsForTrack(){return [...(FAMILY_MODULES[state.track.family]||[]),...(EXTRA_FAMILY_MODULES[state.track.family]||[])].map((q,i)=>({...q,id:q.id||`tm${i+1}`}))}
restore();if(state.track&&state.startedAt&&!state.submitted){if(totalLeft()<=0)submit(true);else{runTimer();render()}}else if(state.track&&state.submitted){globalTimer.classList.remove('hidden');globalTimer.textContent=state.timedOut?'00:00':fmt(Math.max(0,totalLeft()));restartBtn.classList.remove('hidden');results()}else welcome();