(function(){'use strict';
const models={
awful:'Good morning. Today I am going to make a presentation about customer service. Our company was founded in 2007 and has grown steadily over the years. We have several departments and forty-six people in the service team. We reviewed a lot of information and spoke to a number of people. There are various issues that we should perhaps think about. Thank you.',
strong:'Customer complaints have risen by thirty percent in three months. If this continues, we may lose two major accounts worth one point eight crore rupees. I recommend a forty-eight-hour complaint-resolution system. In our pilot, unresolved complaints fell from forty-two to eleven, and the cost was recovered within eight weeks. I need approval today to introduce it across all branches next month.',
delivery:'Two major accounts may leave. I recommend a forty-eight-hour resolution system.'};
const nav=document.getElementById('stageNav');document.querySelectorAll('.stage').forEach((s,i)=>{s.id='stage-'+(i+1);nav.insertAdjacentHTML('beforeend',`<a href="#${s.id}" title="Stage ${i+1}">${i+1}</a>`)});
let seconds=Number(sessionStorage.pplSeconds||0),running=false,tick=null;function drawTime(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.getElementById('elapsed').textContent=m+':'+s;sessionStorage.pplSeconds=seconds}function clock(){if(tick)clearInterval(tick);if(running)tick=setInterval(()=>{seconds++;drawTime()},1000)}document.getElementById('pauseClock').onclick=()=>{running=!running;document.getElementById('pauseClock').textContent=running?'Pause':'Resume';clock()};document.getElementById('startLab').onclick=()=>{running=true;clock();document.getElementById('stage-1').scrollIntoView();};drawTime();
function speak(text,rate=1){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=rate;u.pitch=.96;speechSynthesis.speak(u)}document.querySelectorAll('.speak-model').forEach(b=>b.onclick=()=>speak(models[b.dataset.model],b.dataset.model==='awful'?1.22:.96));
const selected=new Set();document.querySelectorAll('#crimeGrid button').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');selected.has(b)?selected.delete(b):selected.add(b);const right=[...selected].filter(x=>x.dataset.correct==='true').length,wrong=[...selected].filter(x=>x.dataset.correct==='false').length;document.getElementById('crimeFeedback').textContent=right===5&&!wrong?'Exactly. The audience received activity, not a decision.':'You have found '+right+' of the 5 real problems.'});
document.querySelectorAll('#surgery button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));document.getElementById('checkSurgery').onclick=()=>{const buttons=[...document.querySelectorAll('#surgery button')],ok=buttons.every(b=>b.classList.contains('selected')===(b.dataset.keep==='true'));document.getElementById('surgeryResult').textContent=ok?'Good surgery. The decision is now visible.':'Keep only the problem, business consequence and recommendation.'};
document.querySelectorAll('#titleChoice button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#titleChoice button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('titleFeedback').textContent=b.dataset.best?'Yes—the title states the finding.':'That names the topic. It does not state the finding.'});
document.getElementById('hearBuild').onclick=()=>{const vals=[...document.querySelectorAll('#builder input')].map(x=>x.value.trim()).filter(Boolean);speak(vals.length?vals.join('. '):models.strong,.96)};
const questions=['That will cost too much. Why should we approve it?','Where is the evidence that this will work?','We tried something similar before. Why will this be different?','Why should we accept your recommendation rather than wait?','Could you get to the point—what exactly do you need from us?'];let qi=0;document.getElementById('newQuestion').onclick=()=>{qi=(qi+1)%questions.length;document.getElementById('hardQuestion').textContent='“'+questions[qi]+'”';speak(questions[qi],1.03)};
const recordings={};let active=null;async function record(btn){const slot=btn.dataset.slot,status=document.querySelector(`[data-status="${slot}"]`);if(active){if(active.btn===btn)active.rec.stop();else status.textContent='Finish the current recording first.';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],rec=new MediaRecorder(stream);active={btn,rec,stream,chunks,slot};rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const old=recordings[slot];if(old)URL.revokeObjectURL(old);recordings[slot]=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType||'audio/webm'}));status.textContent='Recorded';btn.textContent='🎤 Record again';btn.classList.remove('live');active=null;renderPlayback(slot)};rec.start();btn.textContent='■ Stop recording';btn.classList.add('live');status.textContent='Recording…'}catch{status.textContent='Please allow microphone access.'}}document.querySelectorAll('.record').forEach(b=>b.onclick=()=>record(b));
function playButton(slot){if(!recordings[slot])return '';return `<button class="secondary" data-play="${slot}">▶ Play recording</button>`}function renderPlayback(slot){document.querySelector(`[data-playback="${slot}"]`).innerHTML=playButton(slot);const clone=document.querySelector(`[data-clone="${slot}"]`);if(clone)clone.innerHTML=playButton(slot);document.querySelectorAll(`[data-play="${slot}"]`).forEach(b=>b.onclick=()=>new Audio(recordings[slot]).play())}
document.querySelectorAll('#scorecard input').forEach(x=>x.onchange=()=>{const n=document.querySelectorAll('#scorecard input:checked').length;document.getElementById('scoreResult').textContent=n+'/5'});
document.getElementById('completeLab').onclick=()=>{document.getElementById('certificate').hidden=false;document.getElementById('certificate').scrollIntoView({behavior:'smooth'});running=false;clock();document.querySelectorAll('.stage-nav a').forEach(a=>a.classList.add('done'))};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const n=Number(e.target.dataset.stage);document.querySelectorAll('.stage-nav a').forEach((a,i)=>a.classList.toggle('done',i<n-1))}}),{threshold:.3});document.querySelectorAll('.stage').forEach(s=>observer.observe(s));
})();
