(function(){
'use strict';
const BASE='https://vtqatrhwfvzyodiftvkc.supabase.co';
const KEY='sb_publishable_IJJ9AW79DhOsWlsPK_8pkg_q5Fh7643';
const API=BASE+'/functions/v1/gd-assignment-release';
const ADMIN_KEY='ascent_admin_master_session',TRAINER_KEY='ascent_trainer_session';
let roster=[];
function getSession(){for(const k of [TRAINER_KEY,ADMIN_KEY]){try{const s=JSON.parse(localStorage.getItem(k)||'null');const exp=new Date(s?.expiresAt||s?.expires_at).getTime();if(s?.sessionToken&&Number.isFinite(exp)&&exp>Date.now())return s}catch{}}return null}
const sess=getSession();if(!sess)return;
function loadXlsx(){return new Promise((res,rej)=>{if(window.XLSX)return res();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=res;s.onerror=()=>rej(Error('Excel reader could not load.'));document.head.appendChild(s)})}
function val(o,names){for(const n of names){const k=Object.keys(o).find(x=>String(x).trim().toLowerCase()===n);if(k&&o[k]!=null)return String(o[k]).trim()}return''}
async function parse(file){await loadXlsx();const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});roster=rows.map(r=>({roll_number:val(r,['roll number','roll no','roll','student id','studentid']),name:val(r,['name','student name','full name']),email:val(r,['email','email address'])})).filter(r=>r.roll_number||r.email);return roster}
async function call(body){const r=await fetch(API,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json','X-ASCENT-ADMIN-SESSION':sess.sessionToken},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){const e=Error(d.message||'GD release failed.');e.data=d;throw e}return d}
function topicVals(){return [...document.querySelectorAll('.topicText')].map(x=>x.value.trim()).filter(Boolean)}
function inject(){const h=[...document.querySelectorAll('h2')].find(x=>x.textContent.trim().startsWith('3. Student access'));if(!h)return;const section=h.closest('section');if(!section||document.getElementById('gdRosterFile'))return;const box=document.createElement('div');box.className='field full';box.style.marginTop='14px';box.innerHTML='<label for="gdRosterFile">Student Excel roster</label><input id="gdRosterFile" type="file" accept=".xlsx,.xls,.csv"><div id="gdRosterStatus" class="help">Required for DUGOUT release. Use columns: Roll Number, Name, Email. Only students in this uploaded roster will receive this GD set.</div><div class="btns"><button id="gdPreviewRoster" class="btn secondary" type="button" disabled>Preview matches</button></div><div id="gdMatchPreview" class="status"></div>';section.insertBefore(box,section.querySelector('.btns'));
const file=document.getElementById('gdRosterFile'),preview=document.getElementById('gdPreviewRoster'),rstatus=document.getElementById('gdRosterStatus'),m=document.getElementById('gdMatchPreview');
file.addEventListener('change',async()=>{try{roster=[];if(!file.files[0])return;await parse(file.files[0]);rstatus.textContent=roster.length+' student row(s) loaded from '+file.files[0].name+'.';preview.disabled=!roster.length;releaseOnly.disabled=!roster.length;releaseEmail.disabled=!roster.length}catch(e){rstatus.textContent=e.message}});
preview.onclick=async()=>{try{m.textContent='Matching roster with ASCENT…';const d=await call({action:'match',recipients:roster});m.textContent=d.unmatched?.length?`${d.matched.length} matched; ${d.unmatched.length} unmatched. ${d.unmatched.map(x=>(x.roll_number||x.email)+': '+x.reason).join(' | ')}`:`${d.matched.length} student(s) matched. Ready to release.`}catch(e){m.textContent=e.message}};
async function release(sendEmail){if(!roster.length){m.textContent='Upload the student Excel roster first.';return}const company=companyName.value.trim(),role=roleName.value.trim(),topics=topicVals();if(!company||!role||!topics.length){m.textContent='Company, role and at least one GD topic are required.';return}releaseOnly.disabled=releaseEmail.disabled=true;m.textContent=sendEmail?'Releasing and emailing targeted students…':'Releasing to targeted students…';try{const d=await call({action:'release',company,role,topics,recipients:roster,send_email:sendEmail});studentLink.value='https://clarionprep.com/ascent/gd-dugout-assignments.html';copyLink.disabled=false;m.textContent=`Released to ${d.recipient_count} matched student(s). Only this Excel roster has access.${sendEmail?' Release emails processed.':''}`;}catch(e){m.textContent=e.message;if(e.data?.unmatched?.length)m.textContent+=' '+e.data.unmatched.map(x=>(x.roll_number||x.email)+': '+x.reason).join(' | ')}finally{releaseOnly.disabled=releaseEmail.disabled=false}}
releaseOnly.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();release(false)},true);releaseEmail.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();release(true)},true);
const note=section.querySelector('.note');if(note)note.innerHTML='DUGOUT access is <b>roster-controlled</b>. Upload the student Excel file with this JD set. Only matched ASCENT students in that file receive the released GD Lab set. Practice recordings and results are not stored here.';
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();