const SUPABASE_URL='https://vtqatrhwfvzyodiftvkc.supabase.co';
const SUPABASE_KEY='sb_publishable_IJJ9AW79DhOsWlsPK_8pkg_q5Fh7643';

const PLAN={
  title:'Learning & Development — Placement Readiness Training Plan',
  audience:'Second-year MBA students targeting Learning & Development roles',
  format:'6 trainer-led sessions × 90 minutes + between-session practice',
  outcome:'Prepare students to diagnose a performance gap, design a focused learning intervention, facilitate it clearly, measure impact, and defend recommendations in an L&D interview or case discussion.',
  trainerRule:'Use this as a placement-readiness plan, not as a theory course. Every session must end with visible student evidence: a diagnosis, design artefact, facilitation sample, measurement plan, or defended recommendation.',
  competencyMap:[
    {name:'Performance diagnosis',evidence:'Distinguishes a business/performance problem from a training request; asks for evidence before prescribing training.'},
    {name:'Training Needs Analysis',evidence:'Identifies target population, current behaviour, desired behaviour, causes, constraints and evidence gaps.'},
    {name:'Learning design',evidence:'Writes observable learning outcomes and chooses practice that directly matches the required behaviour.'},
    {name:'Facilitation',evidence:'Explains, questions, demonstrates, checks understanding, manages participation and keeps time.'},
    {name:'Stakeholder communication',evidence:'Clarifies need, pushes back professionally, recommends an approach and states trade-offs.'},
    {name:'Measurement',evidence:'Uses meaningful indicators, separates activity from outcome, and proposes a realistic evaluation plan.'},
    {name:'L&D data literacy',evidence:'Reads simple completion, assessment and performance data without over-claiming impact.'},
    {name:'Adaptability',evidence:'Changes a recommendation when new constraints or evidence appear.'}
  ],
  sessions:[
    {n:1,title:'Think Like L&D: Diagnose Before You Design',time:'90 min',objectives:['Separate a business symptom, performance gap and training need.','Use a simple performance-diagnosis conversation.','Avoid prescribing training before the cause is known.'],flow:[['0–10','Role reality','What entry-level L&D professionals actually do: diagnose, coordinate, design, facilitate, track and communicate.'],['10–25','Symptom vs cause','Use three short cases. Students identify what is known, what is assumed and what must be checked.'],['25–45','Five-question diagnosis','Train: What is happening? What should be happening? Who is affected? What evidence shows the gap? What may be causing it?'],['45–65','Case practice','Teams diagnose “sales staff need communication training” without accepting the request at face value.'],['65–80','Stakeholder challenge','Trainer plays a manager who insists on a workshop. Student must ask for evidence and explain why diagnosis comes first.'],['80–90','Evidence check','Each student gives a 60-second diagnosis and names the next evidence to collect.']],deliverable:'One-page performance-gap diagnosis: symptom, desired state, evidence, possible causes, next data needed.',trainerWatch:['Jumping straight to a workshop','Using vague causes such as “poor attitude”','Confusing low knowledge with every type of performance problem']},
    {n:2,title:'Training Needs Analysis: Turn a Vague Request into a Learning Brief',time:'90 min',objectives:['Run a basic organisation/task/person analysis.','Identify whether the gap is knowledge, skill, behaviour, process, motivation or environment.','Write a usable training brief.'],flow:[['0–15','TNA frame','Organisation need → task/role requirement → person/learner gap. Keep it practical and evidence-led.'],['15–30','Evidence sources','Manager interviews, learner interviews, observation, performance data, quality data, customer feedback, assessments and work samples.'],['30–50','Mini TNA','Students receive six mixed evidence items and decide what they can and cannot conclude.'],['50–70','Write the brief','Target group, current behaviour, desired behaviour, business reason, constraints, evidence, proposed intervention.'],['70–82','Consulting-style recommendation','Answer first → 2–3 reasons → evidence → risk/condition → next action.'],['82–90','Peer review','Is the proposed training solving the demonstrated gap?']],deliverable:'Training Needs Brief plus a 90-second recommendation to the stakeholder.',trainerWatch:['Treating survey preference as proof of need','Collecting data without a decision question','Recommending training for a process or incentive problem']},
    {n:3,title:'Design Learning that Changes Behaviour',time:'90 min',objectives:['Write observable learning outcomes.','Match teaching method and practice to the behaviour required.','Build a short learning sequence with check-for-learning.'],flow:[['0–15','Outcome quality','Replace “understand/know” with observable behaviour: explain, analyse, demonstrate, handle, decide, create.'],['15–30','Design backwards','Job behaviour → practice task → feedback → input/model → assessment.'],['30–45','Method choice','When to use demonstration, case, role-play, simulation, coached practice, job aid or self-study.'],['45–65','Design sprint','Create a 20-minute module for a real workplace skill.'],['65–78','Check learning','Write one performance-based check, not a recall quiz.'],['78–90','Design defence','Students explain why each activity exists and what evidence it will produce.']],deliverable:'20-minute learning design containing outcome, input/model, practice, feedback and assessment.',trainerWatch:['Too much content','Activities that are fun but unrelated to the outcome','Objectives that cannot be observed or assessed']},
    {n:4,title:'Facilitation & Trainer Communication',time:'90 min',objectives:['Open a session with purpose and relevance.','Give short explanations and clear instructions.','Question, listen, correct and involve learners professionally.'],flow:[['0–15','Strong opening','Hook → relevance → credibility → destination. Keep it learner-facing.'],['15–30','Explain clearly','One idea at a time; Point → Reason → Example; then check understanding.'],['30–45','Instructions','Task, time, output, success standard. Students practise giving a 20-second instruction.'],['45–65','Micro-facilitation','Each student teaches a 4-minute segment and runs one short practice.'],['65–78','Difficult moments','Silence, dominant learner, wrong answer, disagreement, off-topic question, time pressure.'],['78–90','Feedback','Trainer scores clarity, structure, learner involvement, listening, correction and time control.']],deliverable:'Recorded 4-minute micro-facilitation plus trainer rubric.',trainerWatch:['Lecturing continuously','Asking “understood?” instead of checking performance','Giving unclear activity instructions','Correcting in a way that embarrasses the learner']},
    {n:5,title:'Measure Learning and Business Impact Without Over-Claiming',time:'90 min',objectives:['Separate participation, learning, behaviour and business outcome.','Choose leading and lagging indicators.','Build a simple evaluation plan and interpret evidence cautiously.'],flow:[['0–15','Four evidence levels','Reaction/participation, learning, behaviour/application, business result. Explain that attendance is not impact.'],['15–30','Metric quality','Baseline, target, measurement point, comparison, confounders.'],['30–50','Data case','Students interpret completion, assessment and performance data and identify what can honestly be claimed.'],['50–68','Evaluation design','For the Session 3 intervention, create measures before, immediately after and 30 days later.'],['68–80','Dashboard language','Rewrite exaggerated claims such as “training increased sales” into evidence-safe statements.'],['80–90','Manager update','60-second result update: result, evidence, limitation, recommendation.']],deliverable:'Evaluation plan with baseline, measures, timing, owner and decision rule.',trainerWatch:['Equating completion with competence','Claiming causation from correlation','Collecting metrics that do not affect a decision']},
    {n:6,title:'L&D Placement Simulation: Diagnose, Design, Defend',time:'90 min',objectives:['Integrate diagnosis, design, facilitation and measurement.','Respond when new evidence changes the case.','Defend an L&D recommendation in an interview-style conversation.'],flow:[['0–10','Brief','Candidate receives a one-page business problem and training request.'],['10–25','Individual diagnosis','Identify the gap, assumptions, evidence required and likely causes.'],['25–40','Intervention design','Propose objective, audience, method, practice and measure.'],['40–55','New information','Trainer introduces a constraint that weakens the first solution. Candidate must revise the recommendation.'],['55–75','Panel defence','5-minute recommendation + 5-minute questions per student/team.'],['75–85','Behavioural PI link','Answer: Tell me about a time you identified a learning need / changed an approach / handled a difficult learner or stakeholder.'],['85–90','Placement action','Trainer assigns the next development action from the rubric.']],deliverable:'Capstone L&D case pack: diagnosis, learning brief, 20-minute design, evaluation plan and defended recommendation.',trainerWatch:['Defending the first answer after evidence changes','Using L&D jargon without business meaning','Weak connection between diagnosis, intervention and metric']}
  ],
  scoring:{scale:'Score each area 1–5. A student is placement-ready when no critical area is below 3 and the overall profile is at least 3.5/5.',areas:[['Problem diagnosis','Separates symptom from cause; identifies evidence needed.'],['TNA quality','Defines current state, desired behaviour, population, cause and constraints.'],['Learning design','Outcome, method, practice and assessment align.'],['Facilitation','Clear, structured, involving, responsive and time-controlled.'],['Stakeholder communication','Recommendation-first, evidence-based, professional pushback.'],['Measurement','Chooses decision-useful metrics and avoids false impact claims.'],['Adaptability','Revises thinking when evidence or constraints change.'],['Professional communication','Clear structure, concise language, appropriate tone and next action.']]},
  remediation:[['Low structured problem solving','Repeat Sessions 1–2 using two fresh business cases before any new theory.'],['Low communication','Repeat the recommendation and stakeholder segments in Sessions 2, 4 and 6; require Point → Reason → Evidence/Example → Action.'],['Low data interpretation','Use the Session 5 case plus two short tables/charts; student must state insight, limitation and next question.'],['Low judgement/prioritisation','Force ranking of causes/interventions by impact, evidence and feasibility; student must defend first priority.'],['Low adaptability','Use “new information” interruptions in Sessions 1, 2 and 6 and score whether the student genuinely revises the answer.'],['Low verbal reasoning','Require 60–90 second summaries after every case: conclusion first, then two supporting reasons.']],
  placementQuestions:['A manager asks for communication training. What would you do before designing it?','How would you conduct a basic training needs analysis?','How do you decide whether training is the right solution?','Write one good learning objective for a workplace skill and explain how you would assess it.','How would you handle a participant who dominates the session?','How would you measure whether a programme worked?','What would you do if learners liked a programme but job performance did not improve?','A stakeholder rejects your recommendation. How would you respond?','Tell me about a time you changed your approach after receiving new evidence.','What L&D metric would you show a business head, and why?'],
  trainerClose:'The purpose is not to make the student sound like an experienced L&D manager. It is to show credible entry-level judgement: diagnose before designing, connect learning to work, communicate clearly, use evidence carefully, and adapt when facts change.'
};

function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}

export async function onRequestGet({request}){
  const auth=request.headers.get('authorization')||'';
  if(!auth.startsWith('Bearer '))return json({error:'Trainer sign-in required.'},401);
  const headers={apikey:SUPABASE_KEY,authorization:auth};
  const userRes=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers});
  if(!userRes.ok)return json({error:'Trainer session is invalid or expired.'},401);
  const user=await userRes.json();
  if(!user?.id)return json({error:'Trainer session is invalid.'},401);
  const profileRes=await fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=role,active`,{headers:{...headers,accept:'application/json'}});
  if(!profileRes.ok)return json({error:'Unable to verify trainer role.'},403);
  const rows=await profileRes.json();
  const profile=Array.isArray(rows)?rows[0]:null;
  const role=String(profile?.role||'').toLowerCase();
  if(!profile||profile.active===false||!['trainer','admin'].includes(role))return json({error:'Trainer or admin access only.'},403);
  return json({plan:PLAN});
}
