import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")||"",SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(["https://clarionprep.com","https://www.clarionprep.com","https://pcl-professional-communication-lab.pages.dev","https://profile-review.manutelw.workers.dev","https://cat.clarionprep.com"]);
const clean=(v:unknown)=>String(v??"").trim();
function headers(req:Request){const o=clean(req.headers.get("origin"));return{"Access-Control-Allow-Origin":ORIGINS.has(o)?o:"https://clarionprep.com","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
const out=(req:Request,b:Record<string,unknown>,s=200)=>new Response(JSON.stringify(b),{status:s,headers:headers(req)});
function bearer(req:Request){const h=clean(req.headers.get("authorization"));return h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():""}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});const origin=clean(req.headers.get("origin"));if(origin&&!ORIGINS.has(origin))return out(req,{ok:false,message:"Origin not allowed."},403);if(req.method!=="POST")return out(req,{ok:false,message:"Use POST."},405);try{const token=bearer(req);if(!token)return out(req,{ok:false,code:"LOGIN_REQUIRED",message:"Sign in to ClarionPrep."},401);const {data:{user},error}=await db.auth.getUser(token);if(error||!user)return out(req,{ok:false,code:"INVALID_SESSION",message:"Your ClarionPrep session has expired."},401);const b=await req.json().catch(()=>({})),product=clean(b.product_code).toUpperCase(),consume=clean(b.action).toUpperCase()==="CONSUME";if(!product)return out(req,{ok:false,message:"Product is required."},400);const {data:e,error:ee}=await db.from("clarion_product_entitlements").select("id,product_code,status,expires_at,usage_limit,usage_used").eq("user_id",user.id).eq("product_code",product).maybeSingle();if(ee)throw ee;if(!e||e.status!=="ACTIVE")return out(req,{ok:false,code:"ACCESS_REQUIRED",message:"This product is not active on your account."},403);if(new Date(e.expires_at)<=new Date())return out(req,{ok:false,code:"ACCESS_EXPIRED",message:"Your access has expired."},403);if(e.usage_limit!==null&&Number(e.usage_used)>=Number(e.usage_limit))return out(req,{ok:false,code:"USAGE_LIMIT_REACHED",message:"You have used all attempts included with this access."},403);let used=Number(e.usage_used);if(consume&&e.usage_limit!==null){const {data:u,error:ue}=await db.from("clarion_product_entitlements").update({usage_used:used+1,updated_at:new Date().toISOString()}).eq("id",e.id).eq("usage_used",used).lt("usage_used",e.usage_limit).select("usage_used").maybeSingle();if(ue)throw ue;if(!u)return out(req,{ok:false,code:"USAGE_CONFLICT",message:"Please retry. Your usage changed in another session."},409);used=Number(u.usage_used)}return out(req,{ok:true,product_code:product,email:user.email,expires_at:e.expires_at,usage_limit:e.usage_limit,usage_used:used,remaining:e.usage_limit===null?null:Math.max(0,Number(e.usage_limit)-used)})}catch(e){console.error("clarion-product-access",e);return out(req,{ok:false,message:"Access could not be checked."},500)}});
